services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_HEAP_OPTS: -Xmx256M